#############################################################################################
#  SET UP  
#############################################################################################
language: bash
sudo: true

# addons:
#   ssh_known_hosts: edautil3.pok.ibm.com
  # apt:
  #   sources:
  #     - sourceline: 'ppa:openafs/stable'
  #   update: true
#     packages:
#       - linux-headers-generic
#       - openafs-client
#       - openafs-modules-dkms
#       - openafs-krb5
#       - openafs-fileserver
#       - openafs-dbserver
#       - krb5-user
#       - krb5-config
#       # - linux-headers-3.13.0-115-generic


os:
  - linux
dist: 
  # - precise
  - trusty
  # - xenial



#####################################################################################################################################
#  BUILD  
#####################################################################################################################################
before_install:
  - sudo add-apt-repository -y ppa:openafs/stable
  - sudo apt-get update -qq

  # Install the dependencies of deb-pkg-tools before running the test suite.
  # For more information about the nasty /dev/random hack, please see:
  # https://github.com/travis-ci/travis-ci/issues/1913#issuecomment-33891474
  - sudo apt-get install --yes dpkg-dev fakeroot lintian python-apt rng-tools
  - sudo rm -f /dev/random
  - sudo mknod -m 0666 /dev/random c 1 9
  - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
  - sudo /etc/init.d/rng-tools restart


  # Installing Linux Headers
  - sudo apt-cache search linux-headers-
  - sudo apt-get -y install -f linux-headers-$(uname -r)
  - sudo apt-get -y install -f linux-headers-generic 


#####################################################################################################################################
  ################### V1
  - sudo apt-get install -y openafs-client openafs-modules-dkms openafs-krb5 krb5-user krb5-config

  ################### V2
  # strangely `openafs-fileserver` doesn't depend on `openafs-dbserver`; `openafs-krb5` provides `asetkey`
  # - sudo apt-get install openafs-fileserver openafs-dbserver openafs-client openafs-modules-dkms openafs-krb5 krb5-user krb5-config

  ################### V3
  # - sudo apt-get install krb5-user openafs-client openafs-krb5 module-assistant
  # - sudo m-a  -i prepare
  # - sudo m-a -i auto-install openafs
  # - sudo modprobe openafs

